workflows:
  my-workflow:
    name: air2thepeople
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      groups:
        - group_name
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - xcode-project build-ipa --project ios/air2thepeople.xcodeproj --scheme air2thepeople
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - postic.stevan@gmail.com
      scripts:
        - echo 'Post-publish script'
