workflows:
  my-workflow:
    name: air2thepeople
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      groups:
        - group_name
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:

      - npm install
      - cd ios && pod install
      - xcodebuild build -workspace ios/air2thepeople.xcworkspace -scheme air2thepeople CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
#      - xcode-project build-ipa --workspace ios/air2thepeople.xcworkspace --scheme air2thepeople

    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - postic.stevan@gmail.com
      scripts:
        - echo 'Post-publish script'
